### ISSUE TITLE
Help Documentation

### ISSUE THREAD

**Issue by KitchM** [yorikvanhavre/FreeCAD-Help#26]
This is all a little confusing.

The Help>Help menu gives popup:
FreeCAD help files not found (/usr/share/doc/freecad-doc/freecad.qhc). You might need to install the FreeCAD documentation package.

I installed the Help in addon manager, where it said that it is old and outdated.  Then it says it is already added in version .22, but that is not currently available.

I restarted and nothing happened.  Later, the addon manager listing changed to say something else.

In all this, there is still no Help in the program.

**Comment by yorikvanhavre** [comment]
What FreeCAD version are you using please?

**Comment by KitchM** [comment]
I am so sorry.  I forgot the required info.  I was using Debian's 19.1 version.  Because it could not be upgraded, I switched to:
[code]
OS: Debian GNU/Linux 11 (bullseye) (XFCE/xfce)
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods: 
  * Help 1.0.3
[/code]

The help installed on this appimage version.  (Even though it was supposed to install on the 19.1 version, it would not.  But that does not matter now.)

Thanks.
