### ISSUE TITLE
did not show images in FreeCAD mdi area in local html or *.md files

### ISSUE THREAD

**Issue by ebrahimraeyat** [yorikvanhavre/FreeCAD-Help#4]
Hi @yorikvanhavre .

I want to show my .md file in FreeCAD mdi area, but it did not show linked images. also did not show linked images in html.

browser works perfectly, I can open it via my chrome browser in windows.

also, when I embed images in html, it shows images in mdi, but this way the volume of html file increases.

Thanks.

**Comment by yorikvanhavre** [comment]
for the html files to find the images, a "base path" must be given. The images are found relatively to that base path. See https://github.com/yorikvanhavre/FreeCAD-Help/blob/main/Help.py#L107

**Comment by ebrahimraeyat** [comment]
I test it, my baseurl is 

`
'C:\\Users\\ebi\\AppData\\Roaming\\FreeCAD\\Mod\\OSAFE\\help/'
`

I changed the code to:
```
baseurl = os.path.dirname(location) + os.sep
```

my base url is:

`
'C:\\Users\\ebi\\AppData\\Roaming\\FreeCAD\\Mod\\OSAFE\\help\\'
`

But, nothing changed. the images did not shown.

thanks.

**Comment by yorikvanhavre** [comment]
Sorry, I got lost and forgot to come back here..
Try adding `file://` before? So your baseurl is: `file://C:\\Users\\ebi\\AppData\\Roaming\\FreeCAD\\Mod\\OSAFE\\help/`
It might also work better if you replace the backslashes by forward slashes like this:`file://C:/Users/ebi/AppData/Roaming/FreeCAD/Mod/OSAFE/help/`

**Comment by ebrahimraeyat** [comment]
Thank you so much. I changed the code, but it still did not show image yet.:

```
baseurl = os.path.dirname(location) + "/"
baseurl = baseurl.replace(os.sep, '/')
baseurl = f'file://{baseurl}'
print(baseurl)
```

```
11:53:15  Help: opening C:\Users\ebi\AppData\Roaming\FreeCAD\Mod\OSAFE\help\import_model.html
11:53:15  file://C:/Users/ebi/AppData/Roaming/FreeCAD/Mod/OSAFE/help/
```

**Comment by yorikvanhavre** [comment]
Ooh I think we need 3 slashes before the C:, sorry.. see https://en.wikipedia.org/wiki/File_URI_scheme#Windows

**Comment by ebrahimraeyat** [comment]
yes, It works now. Thanks.
